version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true # 継続して実行する設定：ポート待ち受けなどしていないとコンテナが終了してしまうためこの設定が必要
